//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dial8ed.Billing {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class GatewayConfig : global::System.Configuration.ApplicationSettingsBase {
        
        private static GatewayConfig defaultInstance = ((GatewayConfig)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new GatewayConfig())));
        
        public static GatewayConfig Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dev")]
        public string GatewayServiceMode {
            get {
                return ((string)(this["GatewayServiceMode"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("87dfdCVP5K")]
        public string DevApiLoginId {
            get {
                return ((string)(this["DevApiLoginId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6NBCfu86ez7755Tr")]
        public string DevTransactionId {
            get {
                return ((string)(this["DevTransactionId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6N6PbajK88")]
        public string LiveApiLoginId {
            get {
                return ((string)(this["LiveApiLoginId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7jRNe53E25p325QJ")]
        public string LiveTransactionId {
            get {
                return ((string)(this["LiveTransactionId"]));
            }
        }
    }
}
